### PR TITLE
Line break feng shui

### PR DESCRIPTION
**Pull request by darrennolan**
Remove extra starting line break at the top of the function.

### CODE REVIEW

**Comment by stowball** [comment]
Hahaha it's my boss' coding convention :( Not that he'll ever see this code

**Comment by seankoji** [comment]
lol you're a monster dazz

**Comment by darrennolan** [comment]
<3

Going to really look to bringing this into our code.  Tired of explaining focus ring isn't a bug.. >_<

Personally I think focus even when not using a keyboard is still crazy valuable.

**Comment by stowball** [comment]
I wouldn't use it everywhere, but it's useful in places such as where you programmatically set `.focus()` on a `<dialog />`, a popup menu or whatever for keyboard users, because "normal, sighted users" don't need to see a big blue halo around a whole element like that.

And you can even use it to always show items that normally only appear on `:hover`. It's not something I actively encourage, but, for example, having an edit button in every table row is a lot of visual noise and actually makes the UI more complex for sighted users.

Oh, and I'm still waiting on that npm PR 😝

**Comment by darrennolan** [comment]
to publish to NPM?

**Comment by stowball** [comment]
Yep :)

**Comment by darrennolan** [comment]
I guess, make me an issue and assign to me.

**Pull request merged**
